apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-redis
  namespace: ambassador
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query-redis
  template:
    metadata:
      labels:
        app: query-redis
    spec:
      containers:
        - name: query-redis
          image: redis
---
apiVersion: v1
kind: Service
metadata:
  name: query-redis-srv
  namespace: ambassador
spec:
  selector:
    app: query-redis
  ports:
    - name: db
      protocol: TCP
      port: 6379
      targetPort: 6379
