apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: query-postgres
  namespace: ambassador
spec:
  selector:
    matchLabels:
      app: query-postgres
  serviceName: query-postgres-srv
  replicas: 1
  template:
    metadata:
      labels:
        app: query-postgres
    spec:
      containers:
        - name: query-postgres
          image: postgres
          volumeMounts:
            - name: postgres-disk
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_PASSWORD
              value: mysecretpassword
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
  volumeClaimTemplates:
    - metadata:
        name: postgres-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: query-postgres-srv
  namespace: ambassador
spec:
  selector:
    app: query-postgres
  type: LoadBalancer
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432
