---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skill
  namespace: ambassador
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skill
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: skill
    spec:
      containers:
      - name: skill
        image: dadtmt/skill
        ports:
        - name: http
          containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: skill
  namespace: ambassador
spec:
  ports:
  - name: http
    port: 80
    targetPort: 5001
  selector:
    app: skill