apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: skill-mongo
  namespace: ambassador
spec:
  selector:
    matchLabels:
      app: skill-mongo
  serviceName: skill-mongo-srv
  replicas: 1
  template:
    metadata:
      labels:
        app: skill-mongo
    spec:
      containers:
        - name: skill-mongo
          image: mongo
          volumeMounts:
            - name: mongo-skill-disk
              mountPath: /var/lib/mongo-skill/data
  volumeClaimTemplates:
    - metadata:
        name: mongo-skill-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: skill-mongo-srv
  namespace: ambassador
spec:
  selector:
    app: skill-mongo
  type: LoadBalancer
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
